// <auto-generated />
namespace JPRSC.HRIS.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddSSSRange1End : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSSSRange1End));
        
        string IMigrationMetadata.Id
        {
            get { return "202303250037555_AddSSSRange1End"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
